REPIC_HOME = 'REPIC_HOME'
VERSION = '0.2.0'
REPIC = 'repic'
REPIC_ENV_NAME = '%s-%s' % (REPIC, VERSION)
REPIC_ENV_ACTIVATION = 'REPIC_ENV_ACTIVATION'
DEFAULT_ACTIVATION_CMD = 'conda activate %s' % REPIC_ENV_NAME

