# Workflow to send master to pypi and tag the branch
name: master to pypi with comments and tag

# Triggers the workflow on push to the master branch
on:
  push:
    branches: [ main ]

jobs:
  call-publish-workflow:
    uses: scipion-em/.github/.github/workflows/publish_and_tag.yml@master
    with:
      folder: repic
    secrets: inherit
